name: ExoPlayer FFmpeg Extension / Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  NDK_VER: 21.4.7075529

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
      - name: Cache NDK
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Install correct NDK
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VER}"
      - name: Build ffmpeg
        run: ./build.sh
      - name: Build extension and publish library locally
        run: ./gradlew :exoplayer-ffmpeg-extension:publishToMavenLocal
