name: AndroidX Media3 FFmpeg Decoder / Publish

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  NDK_VER: 26.1.10909125

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    environment: release
    if: ${{ contains(github.repository_owner, 'jellyfin') || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - name: Cache NDK
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Install correct NDK
        run: sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${NDK_VER}"
      - name: Build ffmpeg
        run: ./build.sh
      - name: Set JELLYFIN_VERSION
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "JELLYFIN_VERSION=$(echo ${GITHUB_REF#refs/tags/v} | tr / -)" >> $GITHUB_ENV
      - name: Build extension and publish library
        run: ./gradlew :media3-ffmpeg-decoder:publish closeAndReleaseSonatypeStagingRepository
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
