name: ExoPlayer FFmpeg Extension / Publish

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  NDK_VER: 21.4.7075529

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    environment: release
    if: ${{ contains(github.repository_owner, 'jellyfin') || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
      - name: Cache NDK
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Install correct NDK
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VER}"
      - name: Build ffmpeg
        run: ./build.sh
      - name: Set JELLYFIN_VERSION
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "JELLYFIN_VERSION=$(echo ${GITHUB_REF#refs/tags/v} | tr / -)" >> $GITHUB_ENV
      - name: Build extension and publish library
        run: ./gradlew :exoplayer-ffmpeg-extension:publish closeAndReleaseSonatypeStagingRepository
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
