name: ExoPlayer FFmpeg Extension / Publish

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  NDK_VER: 21.4.7075529

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    environment: release
    if: ${{ contains(github.repository_owner, 'jellyfin') || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
      - name: Cache NDK
        uses: actions/cache@c17f4bf4666a8001b1a45c09eb7a485c41aa64c3 # v3.2.0
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Install correct NDK
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VER}"
      - name: Build ffmpeg
        run: ./build.sh
      - name: Set JELLYFIN_VERSION
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "JELLYFIN_VERSION=$(echo ${GITHUB_REF#refs/tags/v} | tr / -)" >> $GITHUB_ENV
      - name: Build extension and publish library
        run: ./gradlew :exoplayer-ffmpeg-extension:publish closeAndReleaseSonatypeStagingRepository
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
