name: ExoPlayer FFmpeg Extension Publish

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: release
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.repository == 'jellyfin/jellyfin-exoplayer-ffmpeg-extension' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # tag=v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build ffmpeg
        run: ./build.sh
      - name: Force specific version of cmake to build extension
        run: |
          cmake=(${ANDROID_SDK_ROOT}/cmake/3.10.2*)
          echo cmake.dir="${cmake[0]}" | tee -a local.properties
      - name: Set JELLYFIN_VERSION
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "JELLYFIN_VERSION=$(echo ${GITHUB_REF#refs/tags/v} | tr / -)" >> $GITHUB_ENV
      - name: Build extension and publish library
        run: ./gradlew :exoplayer-ffmpeg-extension:publish closeAndReleaseSonatypeStagingRepository
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
