name: Gradle validate

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/gradl–µ-wrapper.jar'

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
